name: Test Google Drive Integration

on:
  workflow_dispatch:  # Permite ejecutar manualmente
  pull_request:
    paths:
      - 'src/integrations/google_drive.py'
      - 'tests/integrations/test_google_drive.py'

jobs:
  test-drive:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov google-api-python-client google-auth-httplib2 google-auth-oauthlib
        
    - name: Setup Google Credentials
      run: |
        mkdir -p tests/credentials
        echo "$GOOGLE_CREDENTIALS" > tests/credentials/test_google_credentials.json
        echo "$GOOGLE_TOKEN" > tests/credentials/test_google_token.json
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.TEST_GOOGLE_CREDENTIALS }}
        GOOGLE_TOKEN: ${{ secrets.TEST_GOOGLE_TOKEN }}
        
    - name: Run Drive tests
      run: |
        python -m pytest tests/integrations/test_google_drive.py -v --cov=src/integrations/google_drive.py
      env:
        TEST_DRIVE_ROOT_FOLDER: ${{ secrets.TEST_DRIVE_ROOT_FOLDER }}
